version: "2"
services:
  app:
    build:
      # Build an image from the Dockerfile in the current directory
      context: .
    ports:
      - 8080:80
    environment:
      PORT: "80"
      LOG_BUCKET: "rjk-static-logs"
      LOG_PREFIX: "www.franimals.me/"
